# Generated by Django 3.2.11 on 2022-01-21 11:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='qa',
            name='answer',
            field=models.CharField(max_length=255, verbose_name='answer'),
        ),
        migrations.AlterField(
            model_name='qa',
            name='question',
            field=models.CharField(max_length=255, verbose_name='question'),
        ),
    ]
