# Generated by Django 3.2.11 on 2022-01-24 10:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0003_excelfileupload'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='ExcelFileUpload',
            new_name='ExcelFile',
        ),
        migrations.RenameField(
            model_name='excelfile',
            old_name='excel_file_upload',
            new_name='file',
        ),
    ]
